### ISSUE TITLE
Make hex code copying work with enter key and/or spacebar

### ISSUE THREAD

**Issue by edelstone** [edelstone/tints-and-shades#10]
Recently we made the hex color table cells tab-able, but the enter key or spacebar don't initiate a copy like a click of the mouse would. It would be good for usability and access if this functionality existed.

Here is a basic example on how to do this with some Javascript: https://www.w3.org/TR/wai-aria-practices/examples/button/button.html

**Comment by TJScalzo** [comment]
I would be happy to work on this

**Comment by edelstone** [comment]
Sounds good to me. Let's wrap up #11 (which I just commented on) and you can circle back if you want. Always appreciate the help.
