### ISSUE TITLE
Scroll to color codes when sharing a custom link?

### ISSUE THREAD

**Issue by edelstone** [edelstone/tints-and-shades#16]
Since #7 we've had the ability to share links with the hex codes already loaded on the page, for example: https://maketintsandshades.com/#111334.

I'm thinking it might be nice that when sharing a link like this, the page scrolls to the actual color table section with focus on the first table cell, instead of loading at the top of the page.

Feedback welcome.

**Comment by TJScalzo** [comment]
I like this idea. It makes sense to have the same behavior when the page loads with colors as when pressing the button. Also, it gives us the opportunity to consolidate scrolling code.

**Comment by edelstone** [comment]
Closed by #18
