### ISSUE TITLE
Better error messaging

### ISSUE THREAD

**Issue by edelstone** [edelstone/tints-and-shades#3]
Right now the only validation on the form is catching blank submissions. Ideally we'd have some error messaging for other issues.

**Comment by TJScalzo** [comment]
I have noticed an issue that relates to this. Previously generated colors aren't cleared away if the text area is empty when the submit button is pressed. Instead, the page scrolls down to them. Depending on the length of the page, it can scroll enough that the error message is out of view. 

I think colors should be cleared on every button press, and scrolling should be tied specifically to a successful submission of colors.

**Comment by edelstone** [comment]
Agreed, that's a bit sloppy and your suggestions seem like a good way to go.

**Comment by TJScalzo** [comment]
I think it's going to be necessary to stop using the `required` attribute to have the browser check if the text area is empty. Instead there's going to need to be some logic that creates a popup and clears the page of existing colors if the text area is empty. I would be willing to start working on this.

Are there any other possible errors other than an blank submission that would need to be caught?

**Comment by edelstone** [comment]
When I made this issue, the main thing I thought we should audit for would be "thing is not a hex code" but the truth is the tool works fine with junk in it, as long as at least one hex color string is present. So I'm not sure how to handle that.

**Comment by edelstone** [comment]
Like, this works...
<img width="869" alt="Screen Shot 2019-10-15 at 4 07 55 PM" src="https://user-images.githubusercontent.com/8269046/66869902-facd3a80-ef65-11e9-8edd-6d895e2495ef.png">

Would we want to _only_ accept 6 digit hex codes and spaces? Would we want to disallow hashtags? Might make the tool harder to use honestly.

**Comment by edelstone** [comment]
Closed by #15
