### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by edelstone** [edelstone/tints-and-shades#31]
This could help when evaluating tints and shades for dark interfaces. Would be cool if it could remember state for return visits and across pages within the app (/about, /404).

Think of the possibilities! 

<img width="1097" alt="Screen Shot 2020-04-18 at 2 15 20 PM" src="https://user-images.githubusercontent.com/8269046/79669176-61364e00-817f-11ea-8539-33670349cd6b.png">

**Comment by Dorson** [comment]
Made and tested code for exactly that. Great for the night and evening time.

See live demo on GitHub page:

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Have fun, feel free to fork, copy, adopt, port, etc...

**Comment by edelstone** [comment]
Potential designs for this [posted here](https://github.com/edelstone/tints-and-shades/issues/32#issuecomment-625120757).

**Comment by edelstone** [comment]
This is done and closed via commit 0e496ab.
