### ISSUE TITLE
Click color squares to copy Hex value

### ISSUE THREAD

**Issue by edelstone** [edelstone/tints-and-shades#6]
Would be cool if you could click the color square and copy its Hex code to the clipboard.

**Comment by edelstone** [comment]
Looks promising: https://github.com/zenorocha/clipboard.js/

**Comment by pepas24** [comment]
Hi, I'll like to implement this feature, I've used clipbpard.js in [serverless-stack.com](https://serverless-stack.com/) project and works very well
