### ISSUE TITLE
Show feedback when hex code is successfully copied

### ISSUE THREAD

**Issue by edelstone** [edelstone/tints-and-shades#9]
Since #8 we now have the ability to copy hex codes by clicking on a color square. It might be a nice addition to the UX to give some feedback to the user when they've successfully copied a hex code, like a tooltip that says "Copied!" or the copy icon morphs into a green checkmark.

GitHub kind of does both; we could just use one of these ideas...

![SeBVw5LCeA](https://user-images.githubusercontent.com/8269046/66601902-90378b80-eb6e-11e9-9ebf-2df153120c64.gif)

**Comment by TJScalzo** [comment]
This issue can be closed because of pull request #11.

**Comment by edelstone** [comment]
Thanks @TJScalzo, indeed. I thought it would automatically due to your shorthand in the PR. Maybe I need to be the one to do the shorthand.
